language: php
sudo: true

php:
  - 5.4
  - 5.5
  - 5.6

env:
  global:
    - DB=MYSQL CORE_RELEASE=3.1
    - MODULE_PATH=systemmessages

matrix:
  include:
    - php: 5.4
      env: DB=SQLITE CORE_RELEASE=3.1 COVERAGE=1
    - php: 5.5
      env: DB=PGSQL CORE_RELEASE=3.1
    - php: 5.6
      env: DB=SQLITE CORE_RELEASE=3.2
    - php: 5.6
      env: DB=SQLITE CORE_RELEASE=3.4
    - php: 5.6
      env: DB=PGSQL CORE_RELEASE=master
  allow_failures:
    - php: 7.0
    - env: DB=PGSQL CORE_RELEASE=master

before_script:
  - composer self-update
  - phpenv rehash
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss --require "ezyang/htmlpurifier:4.*,silverstripe/cms:~3.1"
  - cd ~/builds/ss

script:
  - "if [ \"$COVERAGE\" = \"0\" ]; then vendor/bin/phpunit $MODULE_PATH/tests/; fi"
  - "if [ \"$COVERAGE\" = \"1\" ]; then vendor/bin/phpunit --coverage-clover=coverage.clover $MODULE_PATH/tests/; fi"

after_script:
    - "if [ \"$COVERAGE\" = \"1\" ]; then mv coverage.clover ~/build/$TRAVIS_REPO_SLUG/; fi"
    - cd ~/build/$TRAVIS_REPO_SLUG
    - wget https://scrutinizer-ci.com/ocular.phar
    - "if [ \"$COVERAGE\" = \"1\" ]; then travis_retry codecov && travis_retry php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi"