---
Name: systemmessageconfig
---
SilverStripe\Control\RequestHandler:
  extensions:
    - ilateral\SilverStripe\SystemMessages\MessageInjector
SilverStripe\Control\Controller:
  extensions:
    - ilateral\SilverStripe\SystemMessages\SystemMessageControllerExtension
SilverStripe\Security\Member:
  extensions:
    - ilateral\SilverStripe\SystemMessages\SystemMessageMemberExtension
